[package]
name = "fit_social"
version = "1.0.0"
authors = []

[addresses]
fit_social = "0x4a1f3e19101055663fc0817ddc6b2dfca28744cdae8203b8ed3da875b07b23c8"

[dev-addresses]
fit_social = "0x2"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
